print("Content-type: text/plain\r\n")
print("\r\n")
print("Query String: "..SERVER["query_string"].."\n")
print("Request Method: "..SERVER["request_method"].."\n")
print("Content Type: "..SERVER["content_type"].."\n")
print("Content Length: "..SERVER["content_length"].."\n")
print("Script Filename: "..SERVER["script_filename"].."\n")
print("Script Name: "..SERVER["script_name"].."\n")
print("Request URI: "..SERVER["request_uri"].."\n")
print("Document URI: "..SERVER["document_uri"].."\n")
print("Document Root: "..SERVER["document_root"].."\n")
print("Server Protocol: "..SERVER["server_protocol"].."\n")
print("Gateway Interface: "..SERVER["gateway_interface"].."\n")
print("Server Software: "..SERVER["server_software"].."\n")
print("Remote Address: "..SERVER["remote_address"].."\n")
print("Remote Port: "..SERVER["remote_port"].."\n")
print("Server Address: "..SERVER["server_address"].."\n")
print("Server Port: "..SERVER["server_port"].."\n")
print("Server Name: "..SERVER["server_name"].."\n")
print("HTTPS: "..SERVER["https"].."\n")
